### PR TITLE
Black check & yaml

### PR DESCRIPTION
**Pull request by bill88t**
On my fork the check does not pass, as it is not actually compliant with black.
Not forcing it as to not create merge conflicts.
Once #101 goes through, we should be good.

### CODE REVIEW

**Comment by vagnum08** [comment]
LGTM

I will merge it after the other one.

**Comment by bill88t** [comment]
Once #101 is merged, I will update this branch to verify the check actually works, just in case.

**Comment by vagnum08** [comment]
Probably it will be okay, but better safe than sorry.

**Comment by bill88t** [comment]
Check now correctly passes. So both states have been verified.

**Comment by vagnum08** [comment]
Cherry picked the commit and pushed it to master.

**Pull request closed without merging**
