### PR TITLE
Fix path transversal vulnerability

### PR DESCRIPTION
**Pull request by vagnum08**
Fix cpupower-gui.helper path transversal vulnerability through dbus variant types for cpu.
Fix priviledge escalation issues.

Closes: #3, #4

### CODE REVIEW

**Comment by lindi2** [comment]
There are a lot of changes in the patch but at least the in_signature change looks good now. Have you considered also using booleans for return values instead of int? Also, does this code handle the rare case where the number of CPUs changes? I can reasonably see this happening only in a virtual machine where this service probably does not make sense but reading one file should be quite cheap.

**Comment by vagnum08** [comment]
I split up read_settings to be more fine grained. I can return boolean but for the case of  update_cpu I want to know the error code.

As for the CPU change, I think you can do it on baremetal by changing the `online` I am reading. I haven't checked this though. But as you say, reading a file is cheap. I will do that.

**Comment by vagnum08** [comment]
I did a quick test and you can change the state of a CPU by either setting 0 or 1 the file `/sys/devices/system/cpu/cpuX/online`.
Then the `/sys/devices/system/cpu/online` looks like this `0-1,3`, if you disable CPU 2 on a four core system.

**Comment by vagnum08** [comment]
It is a lot better now, I think. I refactored the `read_settings` and made it modular. Now the D-BUS helper has a more appropriate API. I removed the `read_settings` from the `__main__` and now the gui queries the helper.

Lastly, the number of CPUs is handled gracefully, you can remove a CPU and it removes it from the list. Also, only the available CPU are included to the drop-down menu.

TODO: List all CPUs and add a checkbox to enable/disable them from the GUI and add a call to D-BUS.

Any thoughts?

**Comment by lindi2** [comment]
Hmm, have you considered using properties for retrieving read-only data? This would have the benefit that the UI could listen for PropertiesChanged signal without having to poll the status or display old data.

**Comment by vagnum08** [comment]
> Hmm, have you considered using properties for retrieving read-only data?

I hadn't thought about it. But after a quick look with d-feet, it does look interesting.

> This would have the benefit that the UI could listen for PropertiesChanged signal without having to poll the status or display old data.

I guess I will have to do some polling on the files at the helper side (maybe inotify will help).

I will look into it, thanks.

**Pull request merged**
